# Generated by Django 4.0.6 on 2022-07-20 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailDomain",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("E", "Enabled"), ("D", "Disabled"), ("X", "Deleted")],
                        default="E",
                        max_length=1,
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("domain_name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmailServer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("E", "Enabled"), ("D", "Disabled"), ("X", "Deleted")],
                        default="E",
                        max_length=1,
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("email_server", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmailUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("E", "Enabled"), ("D", "Disabled"), ("X", "Deleted")],
                        default="E",
                        max_length=1,
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(max_length=200)),
                ("fullname", models.CharField(blank=True, max_length=200)),
                (
                    "active_directory_basedn",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "email_server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vutman.emailserver",
                    ),
                ),
            ],
            options={
                "unique_together": {("username", "email_server")},
            },
        ),
        migrations.CreateModel(
            name="HistoricalEmailUser",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("E", "Enabled"), ("D", "Disabled"), ("X", "Deleted")],
                        default="E",
                        max_length=1,
                    ),
                ),
                ("last_modified", models.DateTimeField(blank=True, editable=False)),
                ("username", models.CharField(max_length=200)),
                ("fullname", models.CharField(blank=True, max_length=200)),
                (
                    "active_directory_basedn",
                    models.CharField(blank=True, max_length=200),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "email_server",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="vutman.emailserver",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical email user",
                "verbose_name_plural": "historical email users",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEmailServer",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("E", "Enabled"), ("D", "Disabled"), ("X", "Deleted")],
                        default="E",
                        max_length=1,
                    ),
                ),
                ("last_modified", models.DateTimeField(blank=True, editable=False)),
                ("email_server", models.CharField(db_index=True, max_length=200)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical email server",
                "verbose_name_plural": "historical email servers",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEmailDomain",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("E", "Enabled"), ("D", "Disabled"), ("X", "Deleted")],
                        default="E",
                        max_length=1,
                    ),
                ),
                ("last_modified", models.DateTimeField(blank=True, editable=False)),
                ("domain_name", models.CharField(db_index=True, max_length=200)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical email domain",
                "verbose_name_plural": "historical email domains",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEmailAlias",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("E", "Enabled"), ("D", "Disabled"), ("X", "Deleted")],
                        default="E",
                        max_length=1,
                    ),
                ),
                ("last_modified", models.DateTimeField(blank=True, editable=False)),
                ("alias_name", models.CharField(max_length=50)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "email_domain",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="vutman.emaildomain",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="vutman.emailuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical email alias",
                "verbose_name_plural": "historical aliases",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="EmailAlias",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("E", "Enabled"), ("D", "Disabled"), ("X", "Deleted")],
                        default="E",
                        max_length=1,
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("alias_name", models.CharField(max_length=50)),
                (
                    "email_domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vutman.emaildomain",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vutman.emailuser",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "aliases",
                "unique_together": {("alias_name", "email_domain")},
            },
        ),
    ]
