# Generated by Django 4.0.6 on 2022-09-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vutman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailalias',
            name='alias_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalemailalias',
            name='alias_name',
            field=models.CharField(max_length=255),
        ),
    ]
